# Default parameters used by the validator to fill missing fields.
# Mirrors the plan in ARCHITECTURE.md (sections 3-4).

generation:
  size: infinitetalk-480
  mode: clip
  frame_num: 81
  max_frame_num: 1000
  sample_steps: 40
  sample_text_guide_scale: 5.0
  sample_audio_guide_scale: 4.0
  motion_frame: 9
  color_correction_strength: 1.0
  use_teacache: false
  teacache_thresh: 0.2
  use_apg: false
  apg_momentum: -0.75
  apg_norm_threshold: 55
  base_seed: 42
  num_persistent_param_in_dit: null
  offload_model: true
  quant: null
  quant_dir: null

output:
  store: s3
  # If using presigned uploads, caller provides final URLs in input.output_config
  # Example:
  #   output_config:
  #     store: s3
  #     video_url: https://s3-presigned-put-url